#!/bin/bash
#


# Stop on errors, print on commands
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

# Sanity check command line options
usage() {
  echo "Usage: $0 (create|destroy|reset|dump)"
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

# Parse argument.  $1 is the first argument
case $1 in
  "create")
    if [[ -e "var/modelcatalog.sqlite3"  ]]; then
        echo "Error: database already exists"
        exit 1
    fi
    mkdir -p var
    sqlite3 var/modelcatalog.sqlite3 < sql/schema.sql
    ;;

  "destroy")
    rm -rf var/modelcatalog.sqlite3 
    ;;

  "reset")
    rm -rf var/modelcatalog.sqlite3 
    sqlite3 var/modelcatalog.sqlite3 < sql/schema.sql
    ;;

  "dump")
    sqlite3 -batch -line var/modelcatalog.sqlite3 'SELECT * FROM modelruns'
    ;;

  *)
    usage
    exit 1
    ;;
esac